package ar.gob.gba.sentinela.vector.service;

import java.sql.DatabaseMetaData;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

import ar.gob.gba.sentinela.vector.dto.PaperIngestionRequest;
import ar.gob.gba.sentinela.vector.dto.PaperIngestionResponse;
import ar.gob.gba.sentinela.vector.dto.PaperSearchRequest;
import ar.gob.gba.sentinela.vector.dto.PaperSearchResult;
import jakarta.annotation.PostConstruct;
import javax.sql.DataSource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class PaperVectorService {

	private static final int DEFAULT_LIMIT = 5;
	private static final int CHUNK_SIZE = 1200;
	private static final int CHUNK_OVERLAP = 180;

	private final JdbcTemplate jdbcTemplate;
	private final DataSource dataSource;
	private final LocalEmbeddingService embeddingService;
	private boolean postgres;
	private boolean vectorEnabled;

	public PaperVectorService(JdbcTemplate jdbcTemplate, DataSource dataSource, LocalEmbeddingService embeddingService) {
		this.jdbcTemplate = jdbcTemplate;
		this.dataSource = dataSource;
		this.embeddingService = embeddingService;
	}

	@PostConstruct
	void initialize() {
		this.postgres = isPostgres();
		if (postgres) {
			try {
				jdbcTemplate.execute("CREATE EXTENSION IF NOT EXISTS vector");
				jdbcTemplate.execute("""
						CREATE TABLE IF NOT EXISTS paper_chunks (
						    id BIGSERIAL PRIMARY KEY,
						    paper_title TEXT NOT NULL,
						    authors TEXT,
						    publication_year INTEGER,
						    source TEXT,
						    chunk_index INTEGER NOT NULL,
						    content TEXT NOT NULL,
						    embedding VECTOR(384),
						    created_at TIMESTAMPTZ DEFAULT now()
						)
						""");
				jdbcTemplate.execute("""
						CREATE INDEX IF NOT EXISTS paper_chunks_embedding_hnsw
						ON paper_chunks USING hnsw (embedding vector_cosine_ops)
						""");
				this.vectorEnabled = true;
				return;
			}
			catch (RuntimeException ex) {
				this.vectorEnabled = false;
			}
		}
		jdbcTemplate.execute("""
				CREATE TABLE IF NOT EXISTS paper_chunks (
				    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				    paper_title VARCHAR(512) NOT NULL,
				    authors VARCHAR(1024),
				    publication_year INTEGER,
				    source VARCHAR(1024),
				    chunk_index INTEGER NOT NULL,
				    content CLOB NOT NULL,
				    embedding_text CLOB,
				    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
				)
				""");
	}

	@Transactional
	public PaperIngestionResponse ingest(PaperIngestionRequest request) {
		if (request.source() != null && !request.source().isBlank() && existsBySource(request.source())) {
			return new PaperIngestionResponse(request.title(), 0, vectorEnabled);
		}
		List<String> chunks = chunk(request.text());
		for (int i = 0; i < chunks.size(); i++) {
			double[] embedding = embeddingService.embed(chunks.get(i));
			if (postgres && vectorEnabled) {
				jdbcTemplate.update("""
						INSERT INTO paper_chunks
						(paper_title, authors, publication_year, source, chunk_index, content, embedding)
						VALUES (?, ?, ?, ?, ?, ?, ?::vector)
						""", request.title(), request.authors(), request.year(), request.source(), i, chunks.get(i),
						embeddingService.toPgVector(embedding));
			}
			else {
				jdbcTemplate.update("""
						INSERT INTO paper_chunks
						(paper_title, authors, publication_year, source, chunk_index, content, embedding_text)
						VALUES (?, ?, ?, ?, ?, ?, ?)
						""", request.title(), request.authors(), request.year(), request.source(), i, chunks.get(i),
						embeddingService.toPgVector(embedding));
			}
		}
		return new PaperIngestionResponse(request.title(), chunks.size(), vectorEnabled);
	}

	@Transactional(readOnly = true)
	public List<PaperSearchResult> search(PaperSearchRequest request) {
		int limit = request.limit() == null ? DEFAULT_LIMIT : Math.max(1, Math.min(request.limit(), 20));
		double[] embedding = embeddingService.embed(request.query());
		if (postgres && vectorEnabled) {
			return jdbcTemplate.query("""
					SELECT id, paper_title, authors, publication_year, source, content,
					       1 - (embedding <=> ?::vector) AS score
					FROM paper_chunks
					ORDER BY embedding <=> ?::vector
					LIMIT ?
					""", (rs, rowNum) -> mapResult(rs), embeddingService.toPgVector(embedding),
					embeddingService.toPgVector(embedding), limit);
		}
		List<PaperSearchResult> rows = jdbcTemplate.query("""
				SELECT id, paper_title, authors, publication_year, source, content, embedding_text
				FROM paper_chunks
				""", (rs, rowNum) -> {
			double score = embeddingService.cosine(embedding, embeddingService.parseVector(rs.getString("embedding_text")));
			return new PaperSearchResult(rs.getLong("id"), rs.getString("paper_title"), rs.getString("authors"),
					(Integer) rs.getObject("publication_year"), rs.getString("source"), rs.getString("content"), score);
		});
		return rows.stream()
				.sorted(Comparator.comparingDouble(PaperSearchResult::score).reversed())
				.limit(limit)
				.toList();
	}

	public boolean isVectorEnabled() {
		return vectorEnabled;
	}

	@Transactional(readOnly = true)
	public boolean existsBySource(String source) {
		Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM paper_chunks WHERE source = ?", Integer.class,
				source);
		return count != null && count > 0;
	}

	private PaperSearchResult mapResult(ResultSet rs) throws SQLException {
		return new PaperSearchResult(rs.getLong("id"), rs.getString("paper_title"), rs.getString("authors"),
				(Integer) rs.getObject("publication_year"), rs.getString("source"), rs.getString("content"),
				rs.getDouble("score"));
	}

	private List<String> chunk(String text) {
		String cleaned = text == null ? "" : text.replaceAll("\\s+", " ").trim();
		List<String> chunks = new ArrayList<>();
		if (cleaned.isBlank()) {
			return chunks;
		}
		int start = 0;
		while (start < cleaned.length()) {
			int end = Math.min(start + CHUNK_SIZE, cleaned.length());
			int boundary = cleaned.lastIndexOf(". ", end);
			if (boundary > start + 400) {
				end = boundary + 1;
			}
			chunks.add(cleaned.substring(start, end).trim());
			if (end >= cleaned.length()) {
				break;
			}
			start = Math.max(0, end - CHUNK_OVERLAP);
		}
		return chunks;
	}

	private boolean isPostgres() {
		try (Connection connection = dataSource.getConnection()) {
			DatabaseMetaData metaData = connection.getMetaData();
			return metaData.getDatabaseProductName().toLowerCase().contains("postgres");
		}
		catch (SQLException ex) {
			return false;
		}
	}
}
